import Contact from '@/Components/Contact/Contact'
import React from 'react'

export const metadata = {
  title: "Contact Page | Construction",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Contact/>
  </>
}

export default page