import Construction from "@/Components/Construction/Construction";
export const metadata = {
  title: "Constructions Page | Construction",
  description: "Generated by create next app",
};
const Constructions = ()=>{
    return<>
<Construction/>
  </>
}
export default Constructions;

