import Project from '@/Components/project/Project'
import React from 'react'
export const metadata = {
  title: "Saved Projects Page | Construction",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Project />
  </>
}

export default page