import Contractor from '@/Components/Contractor/Contractor'
import React from 'react'
export const metadata = {
  title: "Contractor Projects | Construction",
  description: "Generated by create next app",
};
const page = () => {
  return <>
<Contractor />
  </>
}

export default page