import Details from '@/Components/DEtails/Details'
import React from 'react'
export const metadata = {
  title: "Details Page | Construction",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <Details/>
  </>
}

export default page